### ISSUE TITLE
provide an alternative query implementation using ES/Solr

### ISSUE THREAD

**Issue by lsmith77** [jackalope/jackalope#127]
any transport layer should be easily configured to use this implementation for full text search as a replacement for whatever it natively provides. this way users will get easy access to a high performant full text search solution with additional capabilities like facetting that are not covered by PHPCR.

**Comment by dbu** [comment]
we are now planning a large refactoring of jackalope and this should become much easier then. added it to the list of possible search adapters: https://github.com/Jackalope2/jackalope/wiki/Query-Adapters
