### ISSUE TITLE
null values in multivalued properties

### ISSUE THREAD

**Issue by uwej711** [jackalope/jackalope#210]
If you try to store a null value in a mutlivalued property jackalope throws an exception when it tries to convert the null value to the type of the property. According to the spec null values in multivalued fields should be treated the same as null values for properties, i.e. remove the value from the multivalued property (as properties with value null are removed as well). See http://www.day.com/specs/jcr/2.0/10_Writing.html, "10.4.2.5 Multi-value Properties and Null".

* [ ] Create phpcr-api-tests test that stores multivalue with null
* [ ] Fix the issue - i guess right in the Property class on setValue

**Comment by dbu** [comment]
started working on this, but its more tricky than i thought.

**Comment by dbu** [comment]
started working on this in #288

**Comment by dbu** [comment]
i merged the fix for this one. @uwej711 glad if you can check if it works as expected and i did not break anything in the process.
