### ISSUE TITLE
Refactor internal node representation

### ISSUE THREAD

**Issue by dantleech** [jackalope/jackalope#257]
We should use only one well defined way to represent nodes.

Jackalope implementations are currently expected to deal with nodes in 2 different formats.

The first is as a standard PHPCR Node (implementing `PHPCR\NodeInterface`, the second
is a `\stdClass` which represents a node as follows:

````php
stdClass {
    public $property1 => string 'Foo value' // property value
    public $:property1 => string 'String' // property type
    public $property2 => string 'Bar value' // property value
    public $:property2 => string 'String' // property type
}
````

The above is inflexible, unintuitive and difficult to process. It is a legacy of
the original [Jackrabbit implementation](https://github.com/jackalope/jackalope-jackrabbit/issues/4).

One of the limitations is that we cannot store node properties such as Length (useful with binaries).

**Comment by dbu** [comment]
see https://github.com/Jackalope2/jackalope/wiki/Storage-Adapters-and-Node-instantiation/
