### ISSUE TITLE
Is "Referenceable" mixin required now?

### ISSUE THREAD

**Issue by petforsberg** [jackalope/jackalope#281]
Just tried out new dev-master versions of SF / SF CMF bundles (and I cocluded I'll better go with stable ones), and when trying to create any Document of any class, I get the following error after calling the flush():

    You can only change the uuid of newly created nodes that have "referenceable" mixin.

I don't use "referenceable" annotation at all in any of my model classes, and it worked very well with previous bundles' versions. Now it seems to force me to use referencable.

It's from vendor/jackalop/jackalope/src/Jackalope/Node.php setProperty() method.

*UPDATE*: the same seems to  apply to the newest Master version.

This is the content of this method from previous version (1.1) I had - what is seen here is the lack of the throw exception for the "error" (is it?) mentioned above:

    /**
     * {@inheritDoc}
     *
     * @param boolean $validate does the NodeType control throw an exception if
     *      the property can't be set? To use in case of UUID import
     *
     * @api
     */
    public function setProperty($name, $value, $type = PropertyType::UNDEFINED, $validate = true)
    {
        $this->checkState();

        if ($validate) {
            $types = $this->getMixinNodeTypes();
            array_push($types, $this->getPrimaryNodeType());
            if (null !== $value) {
                $exception = null;
                foreach ($types as $nt) {
                    /** @var $nt \Jackalope\NodeType\NodeType */
                    try {
                        $nt->canSetProperty($name, $value, true);
                        $exception = null;
                        break; // exit loop, we found a valid definition
                    } catch (RepositoryException $e) {
                        if (null === $exception) {
                            $exception = $e;
                        }
                    }
                }
                if (null !== $exception) {
                    throw $exception;
                }
            } else {
                // $value is null for property removal
                // if any type forbids, throw exception
                foreach ($types as $nt) {
                    /** @var $nt \Jackalope\NodeType\NodeType */
                    $nt->canRemoveProperty($name, true);
                }
            }
        }

        //try to get a namespace for the set property
        if (strpos($name, ':') !== false) {
            list($prefix) = explode(':', $name);
            //Check if the namespace exists. If not, throw an NamespaceException
            $this->session->getNamespaceURI($prefix);
        }

        if (is_null($value)) {
            if (isset($this->properties[$name])) {
                $this->properties[$name]->remove();
            }

            return null;
        }

        return $this->_setProperty($name, $value, $type, false);
    }

For the moment in order to get it working again with this version, I simply commented it like this, and it works again (Documents are created):

        if ($validate && 'jcr:uuid' === $name && !$this->isNodeType('mix:referenceable')) {
            //throw new ConstraintViolationException('You can only change the uuid of newly created nodes that have "referenceable" mixin.');
        }

**Comment by dbu** [comment]
hm, this sounds like a bug in phpcr-odm rather than jackalope. we may be more strict in validating what is done now, and thus see that we did something illegal that was not prevented in jackalope 1.1.

can you please create a gist with one of your classes including the mapping you use? do you use a `@PHPCR\Uuid` field in your class? are they declared referenceable?

**Comment by petforsberg** [comment]
This is probably the issue here: I don't use referrers, nor referenceable, due to the performance reasons in any of my Model classes. But I do use Uuid, on the other hand (though for no reason at all at the moment, just left it as it was, in case if it was needed later). So the issue might be the assumption that Uuids are used only for referenceable Documents (and these Documents might be then treated as referenceable, even if they are not) - just a quick guess.

I heavily make use of Traits, which act as components, so I'll put a file which : the basic fields for all Documents. It should be seen what's going on thanks to it I think.

Then simply in all of my Document classes I do:

   use TBasicDocument;

**Comment by dbu** [comment]
a uuid is only available if your document is [referenceable](http://doctrine-phpcr-odm.readthedocs.org/en/latest/reference/association-mapping.html#referenceable-documents). its a bug in phpcr-odm metadata validation that it does not complain about the uuid field in a non-referenceable document.

adding ``/** @Document(referenceable=true) **/`` in your documents should fix the issue. in itself, being referenceable should have no notable performance impact.

**Comment by petforsberg** [comment]
Hmm ok, so I'm wondering: if "referenceable" has no impact on performance or anything, is it really necessery to have it set explicitly, since in Doctrine ORM all Entities may have relations by default?

**Comment by dbu** [comment]
all phpcr documents can have parent and child relations. but phpcr has an explicit mix:referenceable type that you need to add to make nodes referenceable. we want to keep this logic in the odm.

**Comment by petforsberg** [comment]
Ok, this is understood. Pls take a look at the updated comment above.

**Comment by dbu** [comment]
i created a pull request on phpcr-odm to output the correct error when this happens: https://github.com/doctrine/phpcr-odm/pull/629
