### ISSUE TITLE
getReferences does not consider the current state in the session

### ISSUE THREAD

**Issue by danrot** [jackalope/jackalope#298]
Discussion about this started in https://github.com/phpcr/phpcr-api-tests/pull/172#issuecomment-148628519

Summed up, the problem is that the `getReferences` also returns references which are not existing in the current session anymore. So if a value from a property is deleted, it will still be returned on the `getReferences` call. Things get even worse when an entire node with a reference to this node is deleted, since an exception is thrown when hydrating the deleted reference.

**Comment by dbu** [comment]
we might attempt some sort of blacklist approach that records deleted
references. maybe also an additional-list for new references that are
not saved yet?

**Comment by danrot** [comment]
Doesn't the object manager already know about deleted and not saved nodes?

**Comment by dbu** [comment]
not sure if it knows them explicitly, or only when calculating the changeset during saving. the nodes definitely know if they have been themself deleted.

**Comment by danrot** [comment]
Well, I was just thinking that's exactly what this variable is for: https://github.com/jackalope/jackalope/blob/master/src/Jackalope/ObjectManager.php#L120

But however, that sounds like a working approach to me.

**Comment by dbu** [comment]
you are right, Item::remove notifies the ObjectManager.

did you also read the phpdoc:

* Note: Keep in mind that a delete is recursive, but we only have the
* explicitly deleted paths in this array. We check on deleted parents
* whenever retrieving a non-cached node.

the same would have to be done with referrers.
