### ISSUE TITLE
Export/Import creates new nodes with jcr:root prefix

### ISSUE THREAD

**Issue by hason** [jackalope/jackalope#308]
If I export documents by ``bin/console doctrine:phpcr:workspace:export documents.xml`` command. Import command `bin/console doctrine:phpcr:workspace:import documents.xml``does not create the same documents. All imported paths are with ``/jcr:root`` prefix.

**Comment by dbu** [comment]
yes, this is as per specification (which is admittedly a bit unexpected). our recommendation is to put all your content under a common root (like /cms) and only export / import that. with an explicit name, it works fine.

the root node also contains history and other system nodes that can not be imported with the commands. you still need a database level backup even when using the workspace export / import if you want to be able to fully recover after a disk failure. the export and import is mainly meant to transfer data between instances (e.g. production to stage, or export a subtree from a staging env and import in production)
