### ISSUE TITLE
Invalid argument when throwing exception for unknown namespace:

### ISSUE THREAD

**Issue by dantleech** [jackalope/jackalope#314]
The namespace collection can be an `ArrayObject`, in which case `array_keys` does not work, causing an error to be produced when an exception should be thrown in the `NodeProcessor`:

```
        if (!isset($this->namespaces[$alias])) {
            throw new NamespaceException(sprintf(
                'Namespace alias "%s" is not known for name "%s", known namespace aliases are: "%s"',
                $alias,
                $name,
                implode('", "', array_keys($this->namespaces))
            ));
        }
    }
```

**Comment by dbu** [comment]
oh, that is stupid that ArrayObject and array don't allow the same things. foreach works nice on both...

so we should check for the type and use whatever method ArrayObject has to get all keys?
