### ISSUE TITLE
Problem with CND files in Jackrabbit

### ISSUE THREAD

**Issue by pavelvondrasek** [jackalope/jackalope#317]
Hi,

I created some node types, document-classes and mapping in XML. In Jackalope DBAL works all good but in Jackalope Jackrabbit if I call Host::getSite() I get blank collection.

My source codes are here: https://gist.github.com/vondrasekpavel/25074ae784ac7393e9e06619585e7208

Screen from Jackalope DBAL:
![snimek obrazovky 2016-09-22 v 14 05 43](https://cloud.githubusercontent.com/assets/7081340/18747441/bbaaecb2-80cd-11e6-9ac8-1f8cb577fa32.png)

Screen from Jackalope Jackrabbit:
![snimek obrazovky 2016-09-22 v 14 06 53](https://cloud.githubusercontent.com/assets/7081340/18747483/e18e432a-80cd-11e6-82bd-fa54347a0afa.png)

Site and Host are created by fixture.

Can you help what i do wrong? Is something wrong with my node type definition?

Thanks!
Pavel

**Comment by dbu** [comment]
hm. the cnd files are not technically needed. its an additional layer of validation when they are used, but everything should work without.

as the issue title is about the CND - can you try with a fresh jackrabbit repository (you can't delete a cnd once its registered) and see if that makes a difference? also, you could use the [phpcr shell](https://github.com/phpcr/phpcr-shell) to see what exactly is in the repository, to see if the odm does not see something, or if really nothing is there.

i assume you would have seen if there are any errors when loading the fixtures? check with the phpcr shell if all the nodes are present as expected in jackrabbit to be sure its something about loading and not about storing.

**Comment by kuzmamar** [comment]
@dbu There are no errors when loading the fixtures. All nodes are stored as expected. The problem must be in loading the data into the ReferrersCollection. The collection is populated correctly when using jackalope-dbal, but is empty when using jackrabbit.

We are using Jackrabbit version 2.10.3.

**Comment by kuzmamar** [comment]
@dbu The storage looks exactly the same in both

jackalope-dbal:

![jackalope-dbal](https://cloud.githubusercontent.com/assets/8044284/18785982/dbfb7580-819b-11e6-82df-303b04d7fe55.png)

jackalope-jackrabbit:

![jackalope-jackrabbit](https://cloud.githubusercontent.com/assets/8044284/18785995/f1f8c0f4-819b-11e6-8954-15197af267ca.png)

Also we need the cdn files exactly for the validation. We are working on our own cms and we want to ensure that all nodes are valid.

**Comment by dbu** [comment]
one thing you could try is using an older version of jackrabbit. there was something about the latest version having a regression. i tried but could not find any indications. maybe try jackrabbit 2.8.2? 
if that is the problem, you could try to open an issue in the jackrrabit jira. if you are using symfony, you should be able to see the phpcr queries and even the http request in the debug toolbar...

**Comment by dbu** [comment]
did you find a solution for this issue?

**Comment by vondrasekpavel** [comment]
No :(
