### ISSUE TITLE
ModeShape

### ISSUE THREAD

**Issue by vondrasekpavel** [jackalope/jackalope#319]
Hi, 

what do you think about Red Hat's implementation of JCR ModeShape (http://modeshape.jboss.org) ? 

Do you plan support it? It has REST API for communication and supports features like node.type.management.overrides.supported and node.type.management.same.name.siblings.supported.

Thanks.
Pavel

**Comment by dbu** [comment]
it would be great to have support, but as far as i know nobody is working on that atm.

as one of the original authors of jackalope, we wanted to get things to work and have a useful content repository implementation for the symfony cmf and other purposes. that part is achieved. unless somebody wants to pay for a jackalope-modeshape implementation, we won't work on that. if you or somebody else wants to work on it, you are of course welcome. i am glad to help understanding how things work, and once the client shapes up, we can move the repository it into the jackalope organization, giving the authors push right on it, if you want that.

**Comment by dbu** [comment]
btw, same name siblings are supported by jackrabbit as well, we did not implement support for the feature in jackalope however. this would require quite some work in the jackalope/jackalope part.

**Comment by vondrasekpavel** [comment]
Ok, thank you for your answer and yes I'm working on ModeShape implementation :)

I tested ModeShape REST API and it looks that it has all functions that I need to create implementation. Now I'm reading Jacklope\Jackrabbit for inspiration and implementing basic methods in Client.php (such as getNode at this time; login, getNodeTypes, and getNamespaces I have done).

So I will send you soon some questions because in some parts I will need your help :)

**Comment by dbu** [comment]
sounds great!

**Comment by vondrasekpavel** [comment]
@dbu can you please close this issue? I will not work on Modeshape because I think improve Dbal will be better :)

**Comment by dbu** [comment]
sounds good. i think you would see the close button as well, as you created the issue. but i hit close now :-)

**Comment by vondrasekpavel** [comment]
Ou sorry I didn't see button my fault :(
