### ISSUE TITLE
path invalid characters (on Jackrabbit)

### ISSUE THREAD

**Issue by dotZoki** [jackalope/jackalope#32]
Since Jackrabbit allows me to add files with "&" character in it I guess Jackalope would also have to allow me to read those paths.

Exception Message: Path is not well-formed or contains invalid characters: /edu/jhu/pha/www/einstein/stuff/einstein&music.pdf

**Comment by muffe** [comment]
This fix seems to be causing problems for me.

I'm using Jackrabbit 2.18.0 with Tomcat 8 in front of it.

When loading my fixtures the process crashes with HTTP Code 400 while trying to reach the following uri:

`http://jackrabbit:8080/server/default/jcr:root/jcr%3Asystem/jcr%3AnodeTypes/mix%3Acreated/jcr%3ApropertyDefinition[2].5.json`

when not replacing the parenthesis in [Client.php#L1877](https://github.com/jackalope/jackalope-jackrabbit/blob/fb62de6ae5bd2dd1cedb80cade78b41cbf649b93/src/Jackalope/Transport/Jackrabbit/Client.php#L1877) the resulting uri can be called just fine resulting in no errors.

Is that a problem with the generated node path, the replacement, or possibly a (mis)configuration of the tomcat?
