### ISSUE TITLE
Jackalope\Query\Row::getValue() disregards empty array as a possible value

### ISSUE THREAD

**Issue by Edvinas9** [jackalope/jackalope#320]
When `Jackalope\Query\Row::getValue()` is dealing with array value - it disregards that it can have no items (= empty array) and always tries to access the first element which results in `Undefined offset: 0` thrown by PHP.

This can be solved by simply checking if the array is not empty before trying to access the first element & if it's empty - just return `null`.

_Note:_ Meanwhile, the error can be suppressed by putting @ symbol before calling a method that internally calls `Row::getValue()`. For example: `$collection = @$repository->getCollection()`. Keep in mind that this is not a good practice and should only be used as a last resort.

**Comment by dbu** [comment]
you mean this line, right? https://github.com/jackalope/jackalope/blob/master/src/Jackalope/Query/Row.php#L166

can you do a pull request that adds a first check to count the $value? ideally, also add a test to https://github.com/phpcr/phpcr-api-tests/ in the query section to make sure it works in all implementations.

**Comment by dbu** [comment]
fixed in #323
