### ISSUE TITLE
Access empty arrays fails due to non-existing index

### ISSUE THREAD

**Issue by danrot** [jackalope/jackalope#322]
When we write an empty array to a field, we cannot access it later in a query anymore, because there is [code accessing the first entry](https://github.com/jackalope/jackalope/blob/5f59291a191a29fab16c124ffe725fbe3976f823/src/Jackalope/Query/Row.php#L165), which fails with a notice undefined offset.

This is happening on jackalope-doctrine-dbal, but not on jackalope-jackrabbit. I guess the empty array should not be written at all, right? Or should there be another check in teh row class?

**Comment by dbu** [comment]
setting a property to null deletes it. but having a multivalue property
with 0 entries does not delete so that should be supported. i think we
should just add a `count($value)` as first check on the line you linked.
can you do a pull request?

**Comment by danrot** [comment]
Fixed in #323
