### ISSUE TITLE
[Need help] The root node has no parent

### ISSUE THREAD

**Issue by godoakbrutal** [jackalope/jackalope#330]
Hello 

I use symfony3 and doctrine
I've got a problem when I want to remove data from backend

I've got error "The root node has no parent"
![screen shot 2560-03-27 at 6 43 31 pm](https://cloud.githubusercontent.com/assets/10972026/24389598/f43796b2-13ac-11e7-8d2f-92ea167ec002.png)

The question is How to fix this error when I want to remove data from backend.

I'm a beginner in programming Plz help T_T

**Comment by hacfi** [comment]
@godoakbrutal How do you remove the data? Manually? Programatically? We need some more insight to what you’re doing exactly to understand the issue and help you fix it.

**Comment by dbu** [comment]
note that the root node itself *can* not be removed. there is a slight chance that instead of an exception telling you its not possible, you end up with this exception when trying to delete the root node. do you try to cascade deletion to the parent?

**Comment by godoakbrutal** [comment]
Oh I'm sorry.
It's my fault about removeImage code.
Thank you
