### ISSUE TITLE
\Jackalope\Node::setProperty does no longer work when a target of a weak reference is missing.

### ISSUE THREAD

**Issue by syeo66** [jackalope/jackalope#334]
I have a code like this:

```php
/* @var $voucher Voucher */
foreach ($vouchers as $voucher) {
    $candidate = $voucher->getCandidate();
        if (empty($candidate)) {
                /* @var $voucherNode \Jackalope\Node */
                $voucherNode = $voucher->getNode();
                $voucherNode->setProperty('candidate', null);
                $voucher->setCandidate(null);
                $documentManager->persist($voucher);
                $documentManager->flush();
                ++$vouchersCount;
        }
}
```

It worked well till lately. I tracked it down to the changes made in https://github.com/jackalope/jackalope/commit/dec3761eaa22a40ca3e4e7d40bc18ccec029235f 

Property::getValue on line 571 would throw a \PHPCR\ItemNotFoundException which will prevent it from setting a new value (like null in my case).

**Comment by dbu** [comment]
yep, i missed that edge case to the edge case. thanks for the report. please check #335 to see if this fixes it.

**Comment by syeo66** [comment]
@dbu Yes, #335 looks good to me and seems to fix it.
