### ISSUE TITLE
Jackrabbit Oak

### ISSUE THREAD

**Issue by petforsberg** [jackalope/jackalope#336]
@dbu have you perhaps tried Symfony content repository with [Jackrabbit Oak](https://jackrabbit.apache.org/oak/)? Any ideas?

**Comment by dbu** [comment]
we played around with it, but at the time had to use the old jackrabbit
jcr2davex wrapper because oak had no http layer. i did not follow up on
where they moved with oak now, if it would offer an HTTP based remoting
that could be used.

**Comment by petforsberg** [comment]
Thanks.
